name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Q1
      id: q1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q1
        setup-command: ''
        command: python autograder.py -q q1
        input: ''
        expected-output: "Question q1: 3/3"
        comparison-method: contains
        timeout: 3
        max-score: 10
    
    - name: Q2
      id: q2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q2
        setup-command: ''
        command: python autograder.py -q q2
        input: ''
        expected-output: "Question q2: 3/3"
        comparison-method: contains
        timeout: 3
        max-score: 10
    
    - name: Q3
      id: q3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q3
        setup-command: ''
        command: python autograder.py -q q3
        input: ''
        expected-output: "Question q3: 3/3"
        comparison-method: contains
        timeout: 3
        max-score: 10

    - name: Q4
      id: q4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q4
        setup-command: ''
        command: python autograder.py -q q4
        input: ''
        expected-output: "Question q4: 3/3"
        comparison-method: contains
        timeout: 3
        max-score: 10

    - name: Q5
      id: q5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q5
        setup-command: ''
        command: python autograder.py -q q5
        input: ''
        expected-output: "Question q5: 3/3"
        comparison-method: contains
        timeout: 3
        max-score: 10

    - name: Q6
      id: q6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q6
        setup-command: ''
        command: python autograder.py -q q6
        input: ''
        expected-output: "Question q6: 3/3"
        comparison-method: contains
        timeout: 3
        max-score: 10

    - name: Q7
      id: q7
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q7
        setup-command: ''
        command: python autograder.py -q q7
        input: ''
        expected-output: "Question q7: 4/4"
        comparison-method: contains
        timeout: 3
        max-score: 10

    - name: Q8
      id: q8
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Q8
        setup-command: ''
        command: python autograder.py -q q8
        input: ''
        expected-output: "Question q8: 3/3"
        comparison-method: contains
        timeout: 3
        max-score: 10

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        Q1_RESULTS: "${{steps.q1.outputs.result}}"
        Q2_RESULTS: "${{steps.q2.outputs.result}}"
        Q3_RESULTS: "${{steps.q3.outputs.result}}"
        Q4_RESULTS: "${{steps.q4.outputs.result}}"
        Q5_RESULTS: "${{steps.q5.outputs.result}}"
        Q6_RESULTS: "${{steps.q6.outputs.result}}"
        Q7_RESULTS: "${{steps.q7.outputs.result}}"
        Q8_RESULTS: "${{steps.q8.outputs.result}}"
      with:
        runners: q1,q2,q3,q4,q5,q6,q7,q8
